using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClothingWebApp.Models
{
    /// <summary>
    /// Represents a customer in the system
    /// </summary>
    public class Customer
    {
        /// <summary>
        /// Primary key for the customer, auto-generated by the database
        /// </summary>
        public int CustomerId { get; set; }
        
        /// <summary>
        /// Customer's first name
        /// </summary>
        public required string FirstName { get; set; }
        
        /// <summary>
        /// Customer's last name
        /// </summary>
        public required string LastName { get; set; }
        
        /// <summary>
        /// Customer's email address, used for login and communication
        /// </summary>
        public required string Email { get; set; }
        
        /// <summary>
        /// Customer's shipping address
        /// </summary>
        public required string Address { get; set; }
        
        /// <summary>
        /// Customer's hashed password
        /// In a production system, this should be properly hashed and salted
        /// </summary>
        public required string Password { get; set; }
        
        /// <summary>
        /// Computed property that returns the full name of the customer
        /// </summary>
        public string FullName => $"{FirstName} {LastName}";
    }
}