namespace ClothingWebApp.Models;

public class Customer 
{
    public int CustomerId { get; set; } // This will be auto-generated by the database
    public required string FirstName { get; set; }
    public required string LastName { get; set; }
    public required string Email { get; set; }
    public required string Address { get; set; }
    public required string Password { get; set; }

    // Optional convenience property
    public string FullName => $"{FirstName} {LastName}";
}