namespace ClothingWebApp.Models;
public class Payment
{
    public int PaymentId { get; set; } // Auto-generated by DB
    public int OrderId { get; set; }  
    public Order? Order { get; set; } // Make nullable  
    public string PaymentMethod { get; set; } = string.Empty;  
    public bool IsPaid { get; set; } = false;  
}